theme: jekyll-theme-minimal
logo: /assets/img/logoWorks.png

domain: 404N0TAVAILABLE.github.io    
url: https://github.com/404N0TAVAILABLE/TamasMemoryGameJapaneseAlpha.github.io.git
  #baseurl: /TamasMemoryGameJapaneseAlpha
repository: 404N0TAVAILABLE/TamasMemoryGameJapaneseAlpha.github.io.git 

title: Tama's Memory Game Japanese ed.
description: Site created to  profile python game code

show_downloads: "true"

