title: Tama's Memory Game - Japanese 2
logo: /assets/img/logo2.png
description: Memory Game to increase memory retention
repository: 404N0TAVAILABLE/minimal.git
show_downloads: true
google_analytics:


plugins: 
  - jekyll-remote-theme

