title: Tama's Memory Game - Japanese 2
logo: /assets/img/logo2.png
description: Memory Game to increase memory retention
repository: 404N0TAVAILABLE/minimal.git
remote_theme: 404N0TAVAILABLE/minimal
domain: 404N0TAVAILABLE.github.io
url: https://github.com/404N0TAVAILABLE/TamasMemoryGameJapaneseAlpha.github.io.git
baseurl: /TamasMemoryGameJapaneseAlpha/

show_downloads: true
google_analytics:


plugins: 
  - jekyll-remote-theme

